// ═══════════════════════════════════════════════════════════════════
// PRIME DCX instrument reference data.
//
// Single source of truth for the Contract Specifications and Spreads
// pages. Structural values (contract size, lot limits, leverage, margin)
// come from the published account terms and are firm.
//
// ⚠ COMPLIANCE: the `spread` field on each group is an INDICATIVE FLOOR,
// not a quoted rate. Replace these with desk-confirmed figures before the
// site goes live - brief section 8.3 requires compliance sign-off on any
// published spread, execution-speed or liquidity claim. Every table that
// renders `spread` also renders SPREAD_NOTE below it.
// ═══════════════════════════════════════════════════════════════════

export const SPREAD_NOTE =
  'Spreads on ECN and PRIME accounts are variable and move with liquidity, session and volatility. ' +
  'PRO accounts trade the same book with an all-in spread and no commission. ' +
  'Live executable pricing streams inside the platform. Figures on this page are not a quote.';

// Terms that are identical across every instrument and account tier.
export const UNIVERSAL = {
  minLot: '0.01',
  maxLot: '100',
  marginCall: '100%',
  stopOut: '50%',
  execution: 'Market',
  hedging: 'Allowed',
  scalping: 'Allowed',
};

export function spreadFloorLabel(spread, unit) {
  if (unit === 'pips' && Number(spread) === 0) return 'Variable';
  return `${spread} ${unit}`;
}

export const GROUPS = [
  {
    id: 'fx-majors',
    asset: 'Forex',
    name: 'Forex - Majors',
    spread: '0.0',
    unit: 'pips',
    leverage: '1:5000',
    size: '100,000 base units',
    swap: 'Triple on Wednesday',
    hours: 'Mon 00:00 - Fri 22:00 (server time)',
    rows: [
      ['EURUSD', 'Euro / US Dollar'],
      ['GBPUSD', 'British Pound / US Dollar'],
      ['USDJPY', 'US Dollar / Japanese Yen'],
      ['USDCHF', 'US Dollar / Swiss Franc'],
      ['AUDUSD', 'Australian Dollar / US Dollar'],
      ['USDCAD', 'US Dollar / Canadian Dollar'],
      ['NZDUSD', 'New Zealand Dollar / US Dollar'],
    ],
  },
  {
    id: 'fx-minors',
    asset: 'Forex',
    name: 'Forex - Minors and crosses',
    spread: '0.2',
    unit: 'pips',
    leverage: '1:5000',
    size: '100,000 base units',
    swap: 'Triple on Wednesday',
    hours: 'Mon 00:00 - Fri 22:00 (server time)',
    rows: [
      ['EURGBP', 'Euro / British Pound'],
      ['EURJPY', 'Euro / Japanese Yen'],
      ['EURCHF', 'Euro / Swiss Franc'],
      ['EURAUD', 'Euro / Australian Dollar'],
      ['EURCAD', 'Euro / Canadian Dollar'],
      ['EURNZD', 'Euro / New Zealand Dollar'],
      ['GBPJPY', 'British Pound / Japanese Yen'],
      ['GBPCHF', 'British Pound / Swiss Franc'],
      ['GBPAUD', 'British Pound / Australian Dollar'],
      ['GBPCAD', 'British Pound / Canadian Dollar'],
      ['GBPNZD', 'British Pound / New Zealand Dollar'],
      ['AUDJPY', 'Australian Dollar / Japanese Yen'],
      ['AUDNZD', 'Australian Dollar / New Zealand Dollar'],
      ['AUDCAD', 'Australian Dollar / Canadian Dollar'],
      ['AUDCHF', 'Australian Dollar / Swiss Franc'],
      ['CADJPY', 'Canadian Dollar / Japanese Yen'],
      ['CADCHF', 'Canadian Dollar / Swiss Franc'],
      ['CHFJPY', 'Swiss Franc / Japanese Yen'],
      ['NZDJPY', 'New Zealand Dollar / Japanese Yen'],
      ['NZDCAD', 'New Zealand Dollar / Canadian Dollar'],
      ['NZDCHF', 'New Zealand Dollar / Swiss Franc'],
    ],
  },
  {
    id: 'fx-exotics',
    asset: 'Forex',
    name: 'Forex - Exotics',
    spread: '1.5',
    unit: 'pips',
    leverage: '1:1000',
    size: '100,000 base units',
    swap: 'Triple on Wednesday',
    hours: 'Mon 00:00 - Fri 22:00 (server time)',
    rows: [
      ['USDSGD', 'US Dollar / Singapore Dollar'],
      ['USDHKD', 'US Dollar / Hong Kong Dollar'],
      ['USDNOK', 'US Dollar / Norwegian Krone'],
      ['USDSEK', 'US Dollar / Swedish Krona'],
      ['USDPLN', 'US Dollar / Polish Zloty'],
      ['USDCZK', 'US Dollar / Czech Koruna'],
      ['USDHUF', 'US Dollar / Hungarian Forint'],
      ['USDMXN', 'US Dollar / Mexican Peso'],
      ['USDZAR', 'US Dollar / South African Rand'],
      ['USDTRY', 'US Dollar / Turkish Lira'],
      ['USDCNH', 'US Dollar / Offshore Chinese Yuan'],
      ['EURNOK', 'Euro / Norwegian Krone'],
      ['EURSEK', 'Euro / Swedish Krona'],
      ['EURPLN', 'Euro / Polish Zloty'],
      ['EURTRY', 'Euro / Turkish Lira'],
      ['EURZAR', 'Euro / South African Rand'],
      ['GBPSGD', 'British Pound / Singapore Dollar'],
      ['GBPZAR', 'British Pound / South African Rand'],
      ['USDDKK', 'US Dollar / Danish Krone'],
      ['USDILS', 'US Dollar / Israeli Shekel'],
      ['USDTHB', 'US Dollar / Thai Baht'],
      ['EURHUF', 'Euro / Hungarian Forint'],
      ['EURCZK', 'Euro / Czech Koruna'],
      ['EURDKK', 'Euro / Danish Krone'],
      ['EURSGD', 'Euro / Singapore Dollar'],
      ['EURHKD', 'Euro / Hong Kong Dollar'],
      ['GBPTRY', 'British Pound / Turkish Lira'],
      ['GBPPLN', 'British Pound / Polish Zloty'],
      ['GBPNOK', 'British Pound / Norwegian Krone'],
      ['GBPSEK', 'British Pound / Swedish Krona'],
      ['CHFSGD', 'Swiss Franc / Singapore Dollar'],
      ['AUDSGD', 'Australian Dollar / Singapore Dollar'],
      ['NZDSGD', 'New Zealand Dollar / Singapore Dollar'],
      ['SGDJPY', 'Singapore Dollar / Japanese Yen'],
      ['ZARJPY', 'South African Rand / Japanese Yen'],
      ['TRYJPY', 'Turkish Lira / Japanese Yen'],
      ['NOKSEK', 'Norwegian Krone / Swedish Krona'],
      ['NOKJPY', 'Norwegian Krone / Japanese Yen'],
    ],
  },
  {
    id: 'metals',
    asset: 'Commodities',
    name: 'Metals',
    spread: '0.10',
    unit: 'points',
    leverage: '1:2000',
    size: '100 oz (gold), 5,000 oz (silver)',
    swap: 'Triple on Wednesday',
    hours: 'Mon 01:00 - Fri 23:00 (server time)',
    rows: [
      ['XAUUSD', 'Gold / US Dollar'],
      ['XAGUSD', 'Silver / US Dollar'],
      ['XAUEUR', 'Gold / Euro'],
      ['XAGEUR', 'Silver / Euro'],
      ['XPTUSD', 'Platinum / US Dollar'],
      ['XPDUSD', 'Palladium / US Dollar'],
    ],
  },
  {
    id: 'energy',
    asset: 'Commodities',
    name: 'Energy',
    spread: '0.03',
    unit: 'points',
    leverage: '1:500',
    size: '1,000 barrels',
    swap: 'Triple on Wednesday',
    hours: 'Mon 01:00 - Fri 23:00 (server time)',
    rows: [
      ['USOIL', 'WTI Crude Oil'],
      ['UKOIL', 'Brent Crude Oil'],
      ['NATGAS', 'Natural Gas'],
    ],
  },
  {
    id: 'indices',
    asset: 'Indices',
    name: 'Indices',
    spread: '0.4',
    unit: 'points',
    leverage: '1:200',
    size: '1 contract per index point',
    swap: 'Triple on Friday',
    hours: 'Follows the underlying cash session',
    rows: [
      ['US30', 'Dow Jones Industrial Average'],
      ['US500', 'S&P 500'],
      ['NAS100', 'Nasdaq 100'],
      ['US2000', 'Russell 2000'],
      ['UK100', 'FTSE 100'],
      ['GER40', 'DAX 40'],
      ['FRA40', 'CAC 40'],
      ['EU50', 'Euro Stoxx 50'],
      ['ESP35', 'IBEX 35'],
      ['JP225', 'Nikkei 225'],
      ['AUS200', 'ASX 200'],
      ['HK50', 'Hang Seng'],
    ],
  },
  {
    id: 'crypto',
    asset: 'Crypto',
    name: 'Cryptocurrency',
    spread: '0.5',
    unit: 'points',
    leverage: '1:100',
    size: '1 coin',
    swap: 'Charged daily, 7 days a week',
    hours: '24/7, including weekends',
    rows: [
      ['BTCUSD', 'Bitcoin / US Dollar'],
      ['ETHUSD', 'Ethereum / US Dollar'],
      ['XRPUSD', 'Ripple / US Dollar'],
      ['SOLUSD', 'Solana / US Dollar'],
      ['BNBUSD', 'BNB / US Dollar'],
      ['ADAUSD', 'Cardano / US Dollar'],
      ['DOGEUSD', 'Dogecoin / US Dollar'],
      ['LTCUSD', 'Litecoin / US Dollar'],
      ['DOTUSD', 'Polkadot / US Dollar'],
      ['LINKUSD', 'Chainlink / US Dollar'],
      ['AVAXUSD', 'Avalanche / US Dollar'],
      ['XLMUSD', 'Stellar / US Dollar'],
      ['TRXUSD', 'TRON / US Dollar'],
      ['MATICUSD', 'Polygon / US Dollar'],
      ['ATOMUSD', 'Cosmos / US Dollar'],
      ['UNIUSD', 'Uniswap / US Dollar'],
      ['ETCUSD', 'Ethereum Classic / US Dollar'],
      ['FILUSD', 'Filecoin / US Dollar'],
      ['NEARUSD', 'NEAR Protocol / US Dollar'],
      ['APTUSD', 'Aptos / US Dollar'],
      ['ARBUSD', 'Arbitrum / US Dollar'],
      ['OPUSD', 'Optimism / US Dollar'],
      ['INJUSD', 'Injective / US Dollar'],
      ['SUIUSD', 'Sui / US Dollar'],
      ['SHIBUSD', 'Shiba Inu / US Dollar'],
      ['PEPEUSD', 'Pepe / US Dollar'],
      ['BCHUSD', 'Bitcoin Cash / US Dollar'],
      ['XMRUSD', 'Monero / US Dollar'],
      ['AAVEUSD', 'Aave / US Dollar'],
      ['ALGOUSD', 'Algorand / US Dollar'],
      ['VETUSD', 'VeChain / US Dollar'],
      ['ICPUSD', 'Internet Computer / US Dollar'],
      ['HBARUSD', 'Hedera / US Dollar'],
      ['SANDUSD', 'The Sandbox / US Dollar'],
      ['GRTUSD', 'The Graph / US Dollar'],
      ['LDOUSD', 'Lido DAO / US Dollar'],
      ['RNDRUSD', 'Render / US Dollar'],
      ['SEIUSD', 'Sei / US Dollar'],
      ['TIAUSD', 'Celestia / US Dollar'],
      ['MKRUSD', 'Maker / US Dollar'],
      ['CRVUSD', 'Curve DAO / US Dollar'],
    ],
  },
];

export const COUNTS = {
  forex: GROUPS.filter(g => g.asset === 'Forex').reduce((n, g) => n + g.rows.length, 0),
  commodities: GROUPS.filter(g => g.asset === 'Commodities').reduce((n, g) => n + g.rows.length, 0),
  indices: GROUPS.filter(g => g.asset === 'Indices').reduce((n, g) => n + g.rows.length, 0),
  crypto: GROUPS.filter(g => g.asset === 'Crypto').reduce((n, g) => n + g.rows.length, 0),
};
COUNTS.total = COUNTS.forex + COUNTS.commodities + COUNTS.indices + COUNTS.crypto;

// Account tiers, mirrored from the Accounts page so pricing stays consistent.
export const TIERS = [
  { name: 'ECN', spreadFrom: 'Variable', commission: '$7 / lot round turn', best: 'Scalpers and high-frequency execution' },
  { name: 'PRO', spreadFrom: '0.8 pips', commission: '$0', best: 'Zero-commission, straightforward trading' },
  { name: 'PRIME', spreadFrom: 'Variable', commission: '$2 / lot round turn', best: 'Tight spreads with the lowest commission' },
];
